variables:
 UPDATE_REPO: "git@github.com:techart/tao3.git"
test.app:
 stage: test
 tags:
 - docker
 - php81
 script:
 - composer install
 - ./vendor/bin/phpunit --configuration phpunit.xml
include:
 - project: "libs/cicd-includes"
   file: "/templates/.gitlab-ci-packagist.yml"
