image: php:7.3
before_script:
- apt-get -y update && apt-get -y install git zip unzip
- curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
- docker-php-ext-install pdo_mysql
test:app:
 script:
 - composer install
 - ./vendor/bin/phpunit --configuration phpunit.xml
