variables:
 UPDATE_REPO: "git@github.com:techart/tao3.git"
 UPDATE_REPO_BRANCH: "v11"
test.app:
 stage: test
 tags:
 - ssh
 - php82
 script:
 - composer install
 - ./vendor/bin/phpunit --configuration phpunit.xml
include:
 - project: "libs/cicd-includes"
   file: "/templates/.gitlab-ci-packagist-versions.yml"
